### ISSUE TITLE
rouge init max_2 deprecated

### ISSUE THREAD

**Issue by rhoposit** [cbaziotis/seq3#5]
max_n=2
limit_length

```
Total Params: 4.6M
Total Trainable Params: 4.6M
Epoch:1, Batch:100/15800 (1%) [--------------------] Time: 0m 10s (-28m 40s)
Traceback (most recent call last):
  File "models/seq3.py", line 423, in <module>
    train_loss = trainer.train_epoch()
  File "/users/jwilliams/code/seq3/modules/training/trainer.py", line 118, in train_epoch
    c(batch, losses, loss_list, batch_outputs)
  File "models/seq3.py", line 368, in eval_callback
    scores = rouge_file_list(config["data"]["ref_path"], hyps)
  File "./utils/eval.py", line 33, in rouge_file_list
    scores = rouge_lists(refs, hyps_list)
  File "./utils/eval.py", line 17, in rouge_lists
    stemming=True)
TypeError: __init__() got an unexpected keyword argument 'limit_length'
```

**Comment by rhoposit** [comment]
duplicate issue, already solved
use py-rouge
